# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCriteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screeningName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=8)),
                ('agegrp', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'notificationcriteria',
            },
        ),
    ]
