# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_record',
            name='record_create_datetime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='patient_record',
            name='medical_history',
            field=models.TextField(),
        ),
    ]
